/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertcurrency;

/**
 *
 * @author shrad
 */
public class Currency extends javax.swing.JFrame {

    /**
     * Creates new form Currency
     */
    public Currency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        From = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        To = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Convert = new java.awt.Button();
        fromam = new javax.swing.JTextField();
        toam = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Currency Converter");

        From.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        From.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India (Rupee)", "Pakistan (Rupee)", "USA (Dollar)", "Japanese (Yen)", "Canadian (Dollar)", "Russia (Ruble)" }));
        From.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("From Convert");

        To.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        To.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India (Rupee)", "Pakistan (Rupee)", "USA (Dollar)", "Japanese (Yen)", "Canadian (Dollar)", "Russia (Ruble)" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("To Convert");

        Convert.setActionCommand("Convert\n\n");
        Convert.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Convert.setLabel("Convert\n");
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fromam)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(From, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toam)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(To)
                    .addComponent(From))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromActionPerformed
       //  To


//         Russia (Ruble)

      // from
//        India (Rupee)
//        Pakistan (Rupee)
//        USA (Dollar)
//        Japanese (Yen)
//        Canadian (Dollar)
//        Russia (Ruble)
        
    }//GEN-LAST:event_FromActionPerformed

    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertActionPerformed
         String fo = (String) From.getSelectedItem();
         String from = fromam.getText();
         String to = (String) To.getSelectedItem();
         
         if(fo == "India (Rupee)"|| fo == "Pakistan (Rupee)"){
             if(to == "USA (Dollar)"|| to == "Canadian (Dollar)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d * 0.0121923);
                 String data = String.valueOf(item);
                 toam.setText(data);
             }
             else if(to == "Japanese (Yen)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d * 1.66);
                 String data = String.valueOf(item);
                 toam.setText(data);
             } else if(to == "Russia (Ruble)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d * 0.93);
                 String data = String.valueOf(item);
                 toam.setText(data);
             }else{
                 toam.setText(to);
             }
         }else if(fo == "USA (Dollar)"|| fo == "Canadian (Dollar)"){
             if(to == "India (Rupee)"|| to == "Pakistan (Rupee)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d / 0.0121923);
                 String data = String.valueOf(item);
                 toam.setText(data);
             }else if(to == "Japanese (Yen)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d * 136.5);
                 String data = String.valueOf(item);
                 toam.setText(data);
             }else if(to == "Russia (Ruble)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d * 75.82);
                 String data = String.valueOf(item);
                 toam.setText(data);
             }
         }else if(fo == "Japanese (Yen)"){
             if(to == "India (Rupee)"|| to == "Pakistan (Rupee)"){
             double d = Double.parseDouble(from);
                 Double item;
                 item =  (d * 0.60);
                 String data = String.valueOf(item);
                 toam.setText(data);
             }else if(to == "USA (Dollar)" || to == "Canadian (Dollar)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d / 0.0073);
                 String data = String.valueOf(item);
                 toam.setText(data);
             }else if(to == "Russia (Ruble)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d * 0.56);
                 String data = String.valueOf(item);
                 toam.setText(data);
             }else {
                 toam.setText(to);
             }
         }else if(fo == " Russia (Ruble)"){
             if(to == "USA (Dollar)" || to == "Canadian (Dollar)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d / 75.82);
                 String data = String.valueOf(item);
                 toam.setText(data);
             }else if(to == "India (Rupee)"|| to == "Pakistan (Rupee)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d / 0.93);
                 String data = String.valueOf(item);
                 toam.setText(data);
             }else if(to == "Japanese (Yen)"){
                 double d = Double.parseDouble(from);
                 Double item;
                 item =  (d / 0.56);
                 String data = String.valueOf(item);
                 toam.setText(data);
         }else{
                 toam.setText(to);
             }
         }
    }//GEN-LAST:event_ConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Convert;
    private javax.swing.JComboBox<String> From;
    private javax.swing.JComboBox<String> To;
    private javax.swing.JTextField fromam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField toam;
    // End of variables declaration//GEN-END:variables
}
